import React from 'react'

 function Product() {
  return (
    <div> 
        <div class="container my-5">
       
      
       <div class="row">
         <div class="col-lg-4 d-flex flex-column justify-content-center align-items-center">
           <img class="mb-3" src="/asset/frp.svg" alt="Generic placeholder image" width="48" height="48"/>
           <h2>Search </h2>
           <p class="w-75 text-center" >Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.</p>
        
         </div>
         <div class="col-lg-4 d-flex flex-column justify-content-center align-items-center">
           <img class="mb-3" src="/asset/grp.svg" alt="Generic placeholder image" width="56" height="48"/>
           <h2>Select</h2>
           <p class="w-75 text-center">Choose from thousands of options generated by the slogan maker that fit your needs..</p>
      
         </div>
         <div class="col-lg-4 d-flex flex-column justify-content-center align-items-center">
           <img class="mb-3" src="/asset/srp.svg" alt="Generic placeholder image" width="65" height="65"/>
           <h2>Stand out</h2>
           <p class="w-75 text-center">Congrats on your new slogan. It's time to win the world!</p>
         
         </div>
       </div>

       <h1 className=" my-5"> Try our other free products</h1>

      <div class="row row-cols-sm-2 row-cols-md-3 g-4">
      
   <div class="col-sm">
   <div class="card border-0">
   <img class="card-img-top" src="images/sap.png" alt="Card image cap"/>
   <div class="card-body">
     <h5 class="card-title">Card title that wraps to a new line</h5>
     <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
   </div>
 </div>

   </div>
   <div class="col-sm">
   <div class="card border-0">
   <img class="card-img-top" src="images/pink.png" alt="Card image cap"/>
   <div class="card-body">
     <h5 class="card-title">Card title that wraps to a new line</h5>
     <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
   </div>
 </div>

   </div>
   <div class="col-sm">
   <div class="card border-0">
   <img class="card-img-top" src="images/greeny.png" alt="Card image cap"/>
   <div class="card-body">
     <h5 class="card-title">Card title that wraps to a new line</h5>
     <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
   </div>
 </div>

   </div>

   <div class="col-sm">
   <div class="card border-0">
   <img class="card-img-top" src="images/bluei.png" alt="Card image cap"/>
   <div class="card-body">
     <h5 class="card-title">Card title that wraps to a new line</h5>
     <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
   </div>
 </div>

   </div>
      </div>
      </div>
    </div>
  )
}
export default Product;