import './App.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import Navbar from './components/layouts/Navbar';
import Footer from './components/layouts/Footer';

function App() {
  return (
    <div>

    {/* navbar   */}
      <Navbar/> 

    {/* slogan maker */}

 



    {/* main content */}
       <div class="container my-5">
       <div class="containers my-5" >
          <div class="row m-5">
            <h1 className='w-75 '> Free slogan maker </h1>
            <p> Simply enter a term that describes your business, and get up to 1,000 relevant slogans for free.</p>
            <div class="row-auto">
            <label for="text" class="visually-hidden">Word for your slogan</label>
            <input type="text" readonly class="form-control-plaintext" id="static" value="Word for your slogan"/>
            </div>
            <div class="row-auto col-lg-4 mb-4">
            <label for="input" class="visually-hidden">Word for your slogan</label>
            <input type="text" class="form-control" id="inputPassword2" placeholder="Cozy"/>
            </div>
            <div class="row-auto">
            <button type="submit" class="btn btn-primary mb-3">Generate slogans</button>
            </div>
         
         
         
         
         
         
         
          </div>
        </div> 
      
        <div class="row">
          <div class="col-lg-4 d-flex flex-column justify-content-center align-items-center">
            <img class="mb-3" src="/asset/grp.svg" alt="Generic placeholder image" width="140" height="140"/>
            <h2>Search </h2>
            <p class="w-75 text-center" >Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.</p>
         
          </div>
          <div class="col-lg-4 d-flex flex-column justify-content-center align-items-center">
            <img class="mb-3" src="/asset/srp.svg" alt="Generic placeholder image" width="140" height="140"/>
            <h2>Select</h2>
            <p class="w-75 text-center">Choose from thousands of options generated by the slogan maker that fit your needs..</p>
       
          </div>
          <div class="col-lg-4 d-flex flex-column justify-content-center align-items-center">
            <img class="mb-3" src="/asset/frp.svg" alt="Generic placeholder image" width="140" height="140"/>
            <h2>Stand out</h2>
            <p class="w-75 text-center">Congrats on your new slogan. It's time to win the world!</p>
          
          </div>
        </div>

        <h1 className=" my-5"> Try our other free products</h1>

       <div class="row row-cols-sm-2 row-cols-md-3 g-4">
       
    <div class="col-sm">
    <div class="card border-0">
    <img class="card-img-top" src="images/sap.png" alt="Card image cap"/>
    <div class="card-body">
      <h5 class="card-title">Card title that wraps to a new line</h5>
      <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    </div>
  </div>

    </div>
    <div class="col-sm">
    <div class="card border-0">
    <img class="card-img-top" src="images/pink.png" alt="Card image cap"/>
    <div class="card-body">
      <h5 class="card-title">Card title that wraps to a new line</h5>
      <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    </div>
  </div>

    </div>
    <div class="col-sm">
    <div class="card border-0">
    <img class="card-img-top" src="images/greeny.png" alt="Card image cap"/>
    <div class="card-body">
      <h5 class="card-title">Card title that wraps to a new line</h5>
      <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    </div>
  </div>

    </div>

    <div class="col-sm">
    <div class="card border-0">
    <img class="card-img-top" src="images/bluei.png" alt="Card image cap"/>
    <div class="card-body">
      <h5 class="card-title">Card title that wraps to a new line</h5>
      <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    </div>
  </div>

    </div>
       </div>
       </div>
    {/* footer    */}
      <Footer/>
    </div>
  );
}

export default App;
